# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: tokium
# "service" is the name of this project. This will also be added to your AWS resource names.
service: ai-clipping-lambda

frameworkVersion: '4'

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'ap-northeast-1'}
  memorySize: ${self:custom.environments.${self:provider.stage}.memorySize}
  timeout: 900
  
  ecr:
    images:
      appimage:
        path: ./
        platform: linux/amd64
        file: Dockerfile 

  # 環境変数の設定
  environment:
    ENVIRONMENT: ${self:provider.stage}
    LOG_LEVEL: ${self:custom.environments.${self:provider.stage}.logLevel}
    OUTPUT_QUEUE_URL: ${self:custom.environments.${self:provider.stage}.outputQueueUrl}
    GEMINI_MODEL: gemini-2.0-flash
    GOOGLE_CLOUD_REGION: us-central1
    GOOGLE_APPLICATION_CREDENTIALS: ./credential.json
    S3_BUCKET_NAME: ${self:custom.environments.${self:provider.stage}.bucketName}
    LLM_OUTPUT_S3_BUCKET_NAME: ${self:custom.environments.${self:provider.stage}.llmOutputBucketName}
    BUGSNAG_API_KEY: ${env:BUGSNAG_API_KEY}
  
  # IAMロールの設定
  iamRoleStatements:
    # S3へのアクセス権限
    - Effect: Allow
      Action:
        - s3:GetObject
      Resource: "arn:aws:s3:::${self:custom.environments.${self:provider.stage}.bucketName}/*"
    # LLM出力S3バケットへの書き込み権限を追加
    - Effect: Allow
      Action:
        - s3:PutObject
      Resource: "arn:aws:s3:::${self:custom.environments.${self:provider.stage}.llmOutputBucketName}/*"
    # 作成する入力SQSへのアクセス権限を追加
    - Effect: Allow
      Action:
        - sqs:ReceiveMessage
        - sqs:DeleteMessage
        - sqs:GetQueueAttributes
      Resource: !GetAtt InputQueue.Arn # 作成するキューのARNを参照
    # 作成するデッドレターキューへの送信権限を追加
    - Effect: Allow
      Action:
        - sqs:SendMessage
      Resource: !GetAtt InputQueueDLQ.Arn # 作成するDLQのARNを参照
    # outputQueueArn への送信権限を追加
    - Effect: Allow
      Action:
        - sqs:SendMessage
      Resource: ${self:custom.environments.${self:provider.stage}.outputQueueArn}

custom:
  # 環境ごとの設定
  environments:
    dev:
      memorySize: 1024
      logLevel: DEBUG
      inputQueueName: ${self:provider.stage}-${self:service}-input-queue
      inputDLQName: ${self:provider.stage}-${self:service}-input-dlq
      outputQueueArn: arn:aws:sqs:ap-northeast-1:885453572349:development-clipSuggestion-aiSuggestionResultQueue
      outputQueueUrl: https://sqs.ap-northeast-1.amazonaws.com/885453572349/development-clipSuggestion-aiSuggestionResultQueue
      bucketName: national-tax-document-clipping-development
      llmOutputBucketName: ${self:provider.stage}-llm-output-${self:service}
      
    staging:
      memorySize: 1024
      logLevel: INFO
      inputQueueName: ${self:provider.stage}-${self:service}-input-queue
      inputDLQName: ${self:provider.stage}-${self:service}-input-dlq
      outputQueueArn: arn:aws:sqs:ap-northeast-1:885453572349:staging-clipSuggestion-aiSuggestionResultQueue
      outputQueueUrl: https://sqs.ap-northeast-1.amazonaws.com/885453572349/staging-clipSuggestion-aiSuggestionResultQueue
      bucketName: national-tax-document-clipping-staging
      llmOutputBucketName: ${self:provider.stage}-llm-output-${self:service}
      
    prod:
      memorySize: 1024
      logLevel: INFO
      inputQueueName: ${self:provider.stage}-${self:service}-input-queue
      inputDLQName: ${self:provider.stage}-${self:service}-input-dlq
      outputQueueArn: arn:aws:sqs:ap-northeast-1:219825478644:production-clipSuggestion-aiSuggestionResultQueue
      outputQueueUrl: https://sqs.ap-northeast-1.amazonaws.com/219825478644/production-clipSuggestion-aiSuggestionResultQueue 
      bucketName: national-tax-document-clipping-production
      llmOutputBucketName: ${self:provider.stage}-llm-output-${self:service}

functions:
  processDocument:
    image: appimage
    events:
      - sqs:
          batchSize: 1
          arn: !GetAtt InputQueue.Arn # 作成するキューのARNを参照

resources:
  Resources:
    InputQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.environments.${self:provider.stage}.inputQueueName}
        # デッドレターキューの設定を追加
        RedrivePolicy:
          deadLetterTargetArn: !GetAtt InputQueueDLQ.Arn
          maxReceiveCount: 3 # メッセージがDLQに移動するまでの最大受信回数
        # Lambdaのタイムアウト + 1分のバッファ
        VisibilityTimeout: 960

    InputQueueDLQ:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.environments.${self:provider.stage}.inputDLQName}
        # DLQのメッセージ保持期間 (例: 14日間)
        MessageRetentionPeriod: 1209600

    LlmOutputBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.environments.${self:provider.stage}.llmOutputBucketName}
        # 必要に応じて、バージョニング、アクセスコントロール、ライフサイクルルールなどをここに追加します。
        # 例:
        # VersioningConfiguration:
        #   Status: Enabled
        # PublicAccessBlockConfiguration:
        #   BlockPublicAcls: true
        #   IgnorePublicAcls: true
        #   BlockPublicPolicy: true
        #   RestrictPublicBuckets: true

plugins: []
